"""initial

Revision ID: b9cb0c89d802
Revises: 
Create Date: 2024-02-10 16:01:57.715044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import map_scraper


# revision identifiers, used by Alembic.
revision: str = 'b9cb0c89d802'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=100), nullable=False),
    sa.Column('google_maps_api_key', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('map_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('zoom', sa.Float(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('map_segment_tiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('center_lat', sa.Float(), nullable=False),
    sa.Column('center_long', sa.Float(), nullable=False),
    sa.Column('map_segment_id', sa.Integer(), nullable=True),
    sa.Column('img', map_scraper.maps.infra.orm.NumpyArray(), nullable=True),
    sa.ForeignKeyConstraint(['map_segment_id'], ['map_segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_coordinates', 'map_segment_tiles', ['center_lat', 'center_long'], unique=False)
    op.create_index('idx_map_segment_id', 'map_segment_tiles', ['map_segment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_map_segment_id', table_name='map_segment_tiles')
    op.drop_index('idx_coordinates', table_name='map_segment_tiles')
    op.drop_table('map_segment_tiles')
    op.drop_table('map_segments')
    op.drop_table('users')
    # ### end Alembic commands ###
